### ISSUE TITLE
Create OCM VS Code Plugin

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/vscode-ocm-tools#3]
**Description**
In order to improve developer efficiency, a VS Code Plugin should be implemented, enabling developers to more easily work with components and component descriptors.

# OCM IDE-Plugin for VS Code / Featurelist:

## VIEW (read-only)
1. Visualize component network / browse components in a tree view. Root of the tree should be a root component, as configured in the respective Setting (see below)
2. View component details (name, version, references, resouces, jump to source, ...) in a nice popup
3. View/Download raw component descriptor (maybe as a context menu entry within the tree view
4. Verify signature (could also be a context menu entry)
5. Indicate if newer version of a component is available (again could be shown in the tree view)

## MISC:
- Validate a component (are all references available, all local blobs present)(could also be a context menu entry within the tree view)

## SETTINGS / Preferences: 
- CD-Root Path in  OCI Repository
- RSA Key pair for signing
- Credentials...

## Low Prio: EDIT (read-write)
Remark: Editing a Component Descriptor in the IDE is not the default usecase, as Component Descriptors should always be generated within the build of a component, usually "from scratch", getting the next component version information from the build environment. So editing a component is only used when "playing around" with component descriptors, to try things out locally or getting to know the OCM concepts. This is why the whole editing part is only of low prio for the IDE plugin.

- Wizard guiding to a create a useful CD: add source, resource, references
- Create initial CD from "here" (here is current Github project)
- add/remove source/resource/reference
- Create Transport from CD
- transport CTF from A to B
- Delete CDs from registry
- Export steps as OCM CLI commands and/or makefile
- add resource of custom type

## Issues

- [x] open-component-model/ocm#259 
- [x] open-component-model/ocm#260  
- [x] open-component-model/vscode-ocm-tools#9  
- [x] open-component-model/ocm#257 
- [x] open-component-model/vscode-ocm-tools#7
- [x] open-component-model/vscode-ocm-tools#10
- [x] open-component-model/vscode-ocm-tools#5 
- [x] open-component-model/vscode-ocm-tools#11 
- [x] open-component-model/vscode-ocm-tools#6 
- [x] open-component-model/vscode-ocm-tools#16

**Comment by In-Ko** [comment]
All planned issues have been done, so I guess we can close this epic. There are a few issues in the vscode repo, but those are individual feature requests or minor bugs.
